# Generated by Django 5.2.9 on 2025-12-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("google_place_id", models.CharField(max_length=255, unique=True)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(default="Bozeman", max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("user_ratings_total", models.IntegerField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemReviewSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField(blank=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "menu_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summary",
                        to="menus.menuitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="menus.place",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_review_id", models.CharField(max_length=255, unique=True)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("rating", models.IntegerField()),
                ("text", models.TextField(blank=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="menus.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemReviewMention",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relevance_score", models.FloatField(default=1.0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="menus.menuitem",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_mentions",
                        to="menus.review",
                    ),
                ),
            ],
            options={
                "unique_together": {("menu_item", "review")},
            },
        ),
    ]
