# Generated by Django 5.2.9 on 2025-12-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_alter_menuitem_id_alter_menuitemreviewmention_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="place",
        ),
        migrations.AlterUniqueTogether(
            name="menuitemreviewmention",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="menuitemreviewmention",
            name="menu_item",
        ),
        migrations.RemoveField(
            model_name="menuitemreviewmention",
            name="review",
        ),
        migrations.CreateModel(
            name="PlaceRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="ai", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="menus.place",
                    ),
                ),
            ],
            options={
                "ordering": ["place", "rank"],
                "unique_together": {("place", "rank")},
            },
        ),
        migrations.DeleteModel(
            name="MenuItemReviewSummary",
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
        migrations.DeleteModel(
            name="MenuItemReviewMention",
        ),
    ]
